export const laners = [
  {
    name: 'top',
    spell1: 'flash',
    spell2: 'teleport',
    hasSpell1: true,
    hasSpell2: true,
    usedSpell1At: 0,
    usedSpell2At: 0,
    hasIonian: false,
    level: 1,
  },
  {
    name: 'jg',
    spell1: 'flash',
    spell2: 'smite',
    hasSpell1: true,
    hasSpell2: true,
    usedSpell1At: 0,
    usedSpell2At: 0,
    hasIonian: false,
    level: 1,
  },
  {
    name: 'mid',
    spell1: 'flash',
    spell2: 'teleport',
    hasSpell1: true,
    hasSpell2: true,
    usedSpell1At: 0,
    usedSpell2At: 0,
    hasIonian: false,
    level: 1,
  },
  {
    name: 'adc',
    spell1: 'flash',
    spell2: 'heal',
    hasSpell1: true,
    hasSpell2: true,
    usedSpell1At: 0,
    usedSpell2At: 0,
    hasIonian: false,
    level: 1,
  },
  {
    name: 'sup',
    spell1: 'flash',
    spell2: 'ignite',
    hasSpell1: true,
    hasSpell2: true,
    usedSpell1At: 0,
    usedSpell2At: 0,
    hasIonian: false,
    level: 1,
  },
];
